"""memory/core.py — module-level helpers, label constants, and converters
shared by the Memory mixins. No class definitions here."""

from __future__ import annotations

import datetime as dt
import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

CATEGORIES = ("architecture",)

_SAFETY_DETAIL_LIMIT = 200

_AGENTRA_LABEL = "agentra"
_BUG_LABEL = "bug"
_FEATURE_LABEL = "feature"
_STORY_LABEL = "story"
_NEED_HUMAN_LABEL = "need_human"
_BLOCKING_AGENTRA_LABEL = "blocking_agentra"
_STATUS_IN_PROGRESS_LABEL = "status:in-progress"
_STATUS_SHIPPED_LABEL = "status:shipped"
_STATUS_DONE_LABEL = "status:done"
_OBJECTIVE_VARIABLE = "AGENTRA_OBJECTIVE"

# A shipped feature/bug fix has run_id/commit_sha stamped into the issue body
# as structured lines by mark_shipped's body_suffix — parseable from the same
# list call with no per-issue follow-up request.
_SHIPPED_RUN_ID_RE = re.compile(r"^Shipped-Run-ID: (.+)$", re.MULTILINE)
_SHIPPED_COMMIT_RE = re.compile(r"^Shipped-Commit: (.+)$", re.MULTILINE)
_SHIPPED_SESSION_ID_RE = re.compile(r"^Shipped-Session-ID: (.+)$", re.MULTILINE)

# A dashboard submission's title/description split: the short title lives on
# the issue itself; the fuller diagnosis/description is a "Description: ..."
# body line so the backlog list can show substantive text, not an abbreviated
# title. Falls back to title for issues created before this existed.
_DESCRIPTION_RE = re.compile(r"^Description: (.+)$", re.MULTILINE)

# Failure triage: a permanent failure (real defect) becomes a GitHub Issue so
# Discovery Agent prioritizes fixing it next cycle. A transient failure
# (rate limits, max-turns, the Claude Code CLI's contradictory-result quirk —
# see agents/base.py's _CONTRADICTORY_RESULT_SUFFIX) is just logged — a retry
# next cycle IS the fix.
_TRANSIENT_FAILURE_PATTERNS = [
    re.compile(r"Reached maximum number of turns \(\d+\)"),
    re.compile(r"rate.?limit", re.IGNORECASE),
    re.compile(r"usage limit", re.IGNORECASE),
    re.compile(r"session limit", re.IGNORECASE),
    re.compile(r"overloaded", re.IGNORECASE),
    re.compile(r"returned an error result: success"),
]

# Auth/permission failures: no amount of different code fixes these — the fix
# is always a human granting/rotating something outside the repo. Deliberately
# narrow: a false positive wrongly halts the orchestrator; a false negative
# just means a fixable-looking bug gets retried normally.
# No bare \b401\b/\b403\b: confirmed live (issue #17), a Testing Agent report
# mentioning "401 instead of 200" in unrelated prose got classified as
# unfixable and labeled blocking_agentra, halting every future cycle.
_UNFIXABLE_BY_AGENTRA_PATTERNS = [
    re.compile(r"unauthorized", re.IGNORECASE),
    re.compile(r"permission denied", re.IGNORECASE),
    re.compile(r"access.{0,20}not granted", re.IGNORECASE),
    re.compile(r"write access.{0,20}not granted", re.IGNORECASE),
]

_GITIGNORE_CONTENT = """\
# Generated by agentra — do not edit manually.
# Commit the audit trail; ignore per-run logs and test screenshots.

logs/
test_artifacts/
"""


def is_transient_failure(text: str) -> bool:
    return any(p.search(text) for p in _TRANSIENT_FAILURE_PATTERNS)


def cannot_be_fixed_by_agentra(text: str) -> bool:
    return any(p.search(text) for p in _UNFIXABLE_BY_AGENTRA_PATTERNS)


def format_safety_denial_line(tool_name: str, pattern: str, detail: str, limit: int = _SAFETY_DETAIL_LIMIT) -> str:
    """Module-level (not just a Memory method) so agents/safety.py's
    PreToolUse hook — which has no Memory instance or run_id, only the
    ambient run logger from base.py's run_log_scope — can build the same
    line shape that Memory.record_safety_denial does, without new plumbing."""
    truncated = detail if len(detail) <= limit else detail[: limit - 3] + "..."
    return f"[safety] denied tool={tool_name} pattern={pattern!r} detail={truncated!r}"


def _label_names(issue: dict) -> set[str]:
    return {lbl["name"] if isinstance(lbl, dict) else lbl for lbl in issue.get("labels", [])}


def _issue_description(issue: dict) -> str:
    match = _DESCRIPTION_RE.search(issue.get("body") or "")
    return match.group(1) if match else issue["title"]


def _github_bug_to_dict(issue: dict) -> dict:
    # run_id set to the same value as external_id (not None): discovery.py's
    # prompt tells the LLM to reference a known_bug by its run_id
    # ("id=b.get('run_id', '')"), unlike feature_queue entries which use
    # external_id — clear_known_bug() already matches on either, so giving
    # both fields the issue number keeps that resolution path working for
    # GitHub-sourced bugs without changing discovery.py.
    issue_number = str(issue["number"])
    labels = _label_names(issue)
    return {
        "run_id": issue_number,
        "severity": "medium",
        "diagnosis": issue["title"],
        "proposed_fix": issue.get("body") or "",
        "source": "github",
        "external_id": issue_number,
        "html_url": issue.get("html_url"),
        "needs_human": _NEED_HUMAN_LABEL in labels,
        "blocking_agentra": _BLOCKING_AGENTRA_LABEL in labels,
    }


def _github_closed_bug_to_dict(issue: dict) -> dict:
    # Separate from _github_bug_to_dict (open bugs) rather than adding closed_at
    # there — that dict shape is exact-compared in several existing tests, and
    # closed_at is meaningless for an open issue anyway.
    issue_number = str(issue["number"])
    labels = _label_names(issue)
    return {
        "run_id": issue_number,
        "severity": "medium",
        "diagnosis": issue["title"],
        "proposed_fix": issue.get("body") or "",
        "source": "github",
        "external_id": issue_number,
        "html_url": issue.get("html_url"),
        "closed_at": issue.get("closed_at"),
        "status_done": _STATUS_DONE_LABEL in labels,
    }


def _github_feature_to_dict(issue: dict) -> dict:
    return {
        "description": issue["title"],
        "source": "github",
        "external_id": str(issue["number"]),
        "html_url": issue.get("html_url"),
    }


def _github_shipped_to_dict(issue: dict) -> dict:
    body = issue.get("body") or ""
    run_id_m = _SHIPPED_RUN_ID_RE.search(body)
    commit_m = _SHIPPED_COMMIT_RE.search(body)
    session_id_m = _SHIPPED_SESSION_ID_RE.search(body)
    labels = _label_names(issue)
    return {
        "feature": issue["title"],
        "commit_sha": commit_m.group(1) if commit_m else None,
        "run_id": run_id_m.group(1) if run_id_m else None,
        "session_id": session_id_m.group(1) if session_id_m else None,
        "ts": issue.get("closed_at"),
        "updated_at": issue.get("updated_at"),
        "external_id": str(issue["number"]),
        "html_url": issue.get("html_url"),
        "status_done": _STATUS_DONE_LABEL in labels,
    }


def _ensure_gitignore(root: Path) -> None:
    """Write .agentra/.gitignore if it is missing or doesn't ignore both
    logs/ and test_artifacts/ — the latter check retrofits repos that
    already have a committed .gitignore from before test_artifacts/
    (screenshots) existed, so they don't start committing binary blobs."""
    gitignore = root / ".gitignore"
    if gitignore.exists():
        content = gitignore.read_text()
        if "logs/" in content and "test_artifacts/" in content:
            return
    gitignore.write_text(_GITIGNORE_CONTENT)
