"""Persistent memory store, scoped to the target repo being improved.

Mirrors the layout from vision.md section 9: architecture, decisions,
features, metrics, failures. Lives at <repo>/.agentra/memory/ so it travels
with the repo and accumulates across runs.

App-agnostic by design: everything here is plain JSON/YAML files agentra
owns and reads/writes itself. Getting real data INTO these files (customer
feedback from whatever database a given app uses, an objective set via
whatever admin UI a given app has) is the job of a per-app adapter command
(EnvironmentConfig.feedback_fetch_command, invoked by orchestrator.py/
brain.py) -- agentra's own code never talks to Firestore/Postgres/anything
app-specific directly.

Git hygiene
-----------
On first use, Memory writes a .agentra/.gitignore into the target repo so that:

  Committed (audit trail, config)       Not committed (noisy per-run data)
  ──────────────────────────────────    ────────────────────────────────────
  memory/  (architecture, decisions,    logs/  (verbose timestamped traces)
           features, metrics, failures)
  shipped.json
  released.json
  known_bugs.json
  feature_queue.json
  objective.yaml
  feedback_sync_state.json
  environments.yaml
  codebase_spec_commit.json

This means the memory system travels with the repo across clones, CI runners,
and contributors, while run logs stay local.
"""

import datetime as dt
import json
import logging
import re
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

CATEGORIES = ("architecture", "decisions", "features", "metrics", "failures")

_SAFETY_DETAIL_LIMIT = 200


def format_safety_denial_line(tool_name: str, pattern: str, detail: str, limit: int = _SAFETY_DETAIL_LIMIT) -> str:
    """Build the run-log line for a blocked tool call, tagged with a
    '[safety]' channel so it's greppable inside the otherwise-freeform
    per-run log that Memory.log/record_safety_denial write to.

    A module-level function (not just a Memory method) so agents/safety.py's
    PreToolUse hook -- which has no Memory instance or run_id, only the
    ambient run logger from base.py's run_log_scope -- can build the same
    line shape that Memory.record_safety_denial below does, and hand it to
    that logger directly instead of needing new plumbing to call
    record_safety_denial itself.
    """
    truncated = detail if len(detail) <= limit else detail[: limit - 3] + "..."
    return f"[safety] denied tool={tool_name} pattern={pattern!r} detail={truncated!r}"


# Written to <repo>/.agentra/.gitignore on first use. We commit the audit
# trail and config; ignore the verbose per-run logs and binary test
# screenshots that add noise (and, for screenshots, real repo bloat since
# every image is a distinct blob) without audit-trail value in history.
_GITIGNORE_CONTENT = """\
# Generated by agentra — do not edit manually.
# Commit the audit trail; ignore per-run logs and test screenshots.

# ── ignored ──────────────────────────────────────────────────────────────────
logs/
test_artifacts/

# ── tracked (listed for clarity; git tracks everything not ignored) ───────────
# memory/
# shipped.json
# released.json
# known_bugs.json
# feature_queue.json
# objective.yaml
# feedback_sync_state.json
# environments.yaml
"""


def _ensure_gitignore(root: Path) -> None:
    """Write .agentra/.gitignore if it is missing or doesn't ignore
    logs/ or test_artifacts/ -- the latter check retrofits repos that
    already have a committed .gitignore from before test_artifacts/
    (screenshots) existed, so they don't start accidentally committing
    binary screenshot blobs the moment they upgrade."""
    gitignore = root / ".gitignore"
    if gitignore.exists():
        content = gitignore.read_text()
        if "logs/" in content and "test_artifacts/" in content:
            return  # already correct, skip the write
    gitignore.write_text(_GITIGNORE_CONTENT)


# ── GitHub Issues as the authoritative backlog (Phase 2) ──────────────────────
# known_bugs()/feature_queue() read live from GitHub Issues (labels "bug" and
# "enhancement") when the target repo's remote is on github.com and the
# GitHub App is installed with Issues access -- falling back to the local
# known_bugs.json/feature_queue.json mirror otherwise (App not configured,
# not installed on this repo, network/rate-limit failure, or a non-GitHub
# remote). This means a human filing or closing an issue directly on GitHub
# is picked up/dropped by Discovery Agent automatically, without going
# through agentra's dashboard at all -- the actual point of making GitHub
# authoritative. record_known_bug/record_feature_request still also write
# the local JSON mirror on every call (cheap, and the one thing that keeps
# working if GitHub is ever unreachable) with the created issue's number as
# external_id, so clear_known_bug/clear_feature_request can close the right
# issue later even if a caller only has the local record.
_BUG_LABEL = "bug"
_FEATURE_LABEL = "enhancement"

# ── Failure triage: replaces the old write-only memory/failures/*.md ledger
# (confirmed nothing in this codebase ever read it back). A permanent
# failure (a real defect in the work attempted) gets filed via
# record_known_bug -- which creates a real GitHub Issue when the target
# repo has one configured, so Discovery Agent prioritizes fixing it next
# cycle instead of it vanishing into a file nothing reads. A transient
# failure (infra/capacity hiccups: rate/usage limits, max-turns
# exhaustion, the Claude Code CLI's own contradictory-result quirk -- see
# agents/base.py's _CONTRADICTORY_RESULT_SUFFIX) isn't a defect at all; a
# retry next cycle is the fix, not a backlog entry, so it's just logged. ──
_TRANSIENT_FAILURE_PATTERNS = [
    re.compile(r"Reached maximum number of turns \(\d+\)"),
    re.compile(r"rate.?limit", re.IGNORECASE),
    re.compile(r"usage limit", re.IGNORECASE),
    re.compile(r"overloaded", re.IGNORECASE),
    re.compile(r"returned an error result: success"),
]


def is_transient_failure(text: str) -> bool:
    return any(p.search(text) for p in _TRANSIENT_FAILURE_PATTERNS)


def _github_bug_to_dict(issue: dict) -> dict:
    # run_id set to the same value as external_id (not None): discovery.py's
    # prompt tells the LLM to reference a known_bug by its run_id
    # specifically ("id=b.get('run_id', '')"), unlike feature_queue entries
    # which use external_id -- clear_known_bug() already matches on either,
    # so giving both fields the issue number keeps that resolution path
    # working for GitHub-sourced bugs without having to change discovery.py.
    issue_number = str(issue["number"])
    return {
        "run_id": issue_number,
        "severity": "medium",
        "diagnosis": issue["title"],
        "proposed_fix": issue.get("body") or "",
        "source": "github",
        "external_id": issue_number,
    }


def _github_feature_to_dict(issue: dict) -> dict:
    return {
        "description": issue["title"],
        "source": "github",
        "external_id": str(issue["number"]),
    }


class Memory:
    def __init__(self, repo: Path):
        self.repo = repo
        self.root = repo / ".agentra"
        self.memory_root = self.root / "memory"
        self.log_root = self.root / "logs"
        self.shipped_path = self.root / "shipped.json"
        self.released_path = self.root / "released.json"
        self.known_bugs_path = self.root / "known_bugs.json"
        self.feature_queue_path = self.root / "feature_queue.json"
        self.objective_path = self.root / "objective.yaml"
        self.feedback_sync_state_path = self.root / "feedback_sync_state.json"
        self.codebase_spec_commit_path = self.root / "codebase_spec_commit.json"
        self.standups_root = self.root / "standups"
        self.work_updates_path = self.root / "work_updates.json"
        for category in CATEGORIES:
            (self.memory_root / category).mkdir(parents=True, exist_ok=True)
        self.log_root.mkdir(parents=True, exist_ok=True)
        _ensure_gitignore(self.root)

    def write(self, category: str, name: str, content: str) -> Path:
        if category not in CATEGORIES:
            raise ValueError(f"unknown memory category: {category}")
        path = self.memory_root / category / f"{name}.md"
        # The category directory can vanish between __init__ and this call -- e.g.
        # implementation.py's _checkout_feature_branch does `git clean -fd .agentra/`
        # then `git checkout -B <feature_branch>`, and git doesn't track empty
        # directories, so a category with no committed file in it (e.g. a repo's
        # first-ever feature under memory/features/) simply doesn't come back after
        # that checkout. Recreate it defensively rather than assume __init__'s mkdir
        # still holds.
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        return path

    def read(self, category: str, name: str) -> str | None:
        path = self.memory_root / category / f"{name}.md"
        return path.read_text() if path.exists() else None

    def log(self, run_id: str, content: str) -> Path:
        path = self.log_root / f"{run_id}.log"
        self.log_root.mkdir(parents=True, exist_ok=True)
        timestamp = dt.datetime.now(dt.timezone.utc).isoformat()
        with path.open("a") as f:
            f.write(f"[{timestamp}] {content}\n")
        self._log_to_firestore(run_id, timestamp, content)
        return path

    def _log_to_firestore(self, run_id: str, timestamp: str, content: str) -> None:
        # Per-run logs were the one data type the storage audit found with
        # no durable copy anywhere -- .agentra/logs/ is gitignored on
        # purpose (verbose, not audit-trail material) and REPOS_ROOT itself
        # is documented VM-local-only (registry.py), so a run's own log was
        # permanently gone the moment its VM instance rebuilt. Mirrors the
        # same collection every run/signal/agent_step already durably lives
        # in (registry.firestore_client()) -- best-effort and silently
        # skipped if Firestore isn't configured (local dev) or the write
        # fails, exactly like every other Firestore mirror in this
        # codebase: local-first, Firestore durability is a bonus, never a
        # requirement for a cycle to keep running.
        try:
            from agentra import registry

            db = registry.firestore_client()
            if db is None:
                return
            from google.cloud import firestore as gcf

            db.collection("run_logs").document(run_id).set(
                {"lines": gcf.ArrayUnion([f"[{timestamp}] {content}"])}, merge=True
            )
        except Exception:
            logger.warning("log: failed to mirror run %s log line to Firestore", run_id, exc_info=True)

    def record_safety_denial(self, run_id: str, tool_name: str, pattern: str, detail: str) -> Path:
        """Durable audit trail for agents/safety.py's guarded_pre_tool_use:
        every blocked tool call gets a '[safety]'-tagged line in the run's
        log via the same self.log() channel everything else in a cycle
        writes to, instead of the deny decision going back to the SDK with
        zero trace left anywhere. `detail` is the (already truncated)
        command/file_path that tripped `pattern`.

        In practice the hook itself calls format_safety_denial_line directly
        through the ambient run logger (base.py's run_log_scope) rather than
        this method, since it has no Memory instance or run_id of its own --
        see agents/safety.py. This method exists for any caller that *does*
        hold a Memory instance, and to keep the line format defined in one
        place."""
        return self.log(run_id, format_safety_denial_line(tool_name, pattern, detail))

    def shipped_features(self) -> list[dict]:
        """Each entry: {feature, commit_sha, ts} -- commit_sha links the
        dashboard's Shipped list to the actual artifact (a GitHub commit
        URL, built client-side from the app's repo_url + this sha) instead
        of just a description with nothing to click through to. Normalizes
        older shipped.json files (a plain list[str], from before commit_sha
        was tracked) into the same shape with commit_sha=None, so existing
        repos don't need a migration."""
        if not self.shipped_path.exists():
            return []
        raw = json.loads(self.shipped_path.read_text())
        return [
            {"feature": e, "commit_sha": None, "ts": None} if isinstance(e, str) else e
            for e in raw
        ]

    def record_shipped(self, feature: str, commit_sha: str | None = None) -> None:
        features = self.shipped_features()
        if any(f["feature"] == feature for f in features):
            return
        features.append({"feature": feature, "commit_sha": commit_sha, "ts": dt.datetime.now(dt.timezone.utc).isoformat()})
        self.shipped_path.write_text(json.dumps(features, indent=2))

    def released_features(self) -> list[dict]:
        """Each entry: {feature, commit_sha, ts, release_run_id} -- the
        production release ledger. This is intentionally separate from
        shipped_features(): shipped means "implemented and in pre-prod", while
        released means "made it to prod". Older released.json files that might
        only contain a plain list[str] normalize into the same shape."""
        if not self.released_path.exists():
            return []
        raw = json.loads(self.released_path.read_text())
        if not isinstance(raw, list):
            return []
        return [
            {
                "feature": e,
                "commit_sha": None,
                "ts": None,
                "release_run_id": None,
            }
            if isinstance(e, str)
            else e
            for e in raw
        ]

    def record_released(
        self,
        feature: str,
        release_run_id: str,
        commit_sha: str | None = None,
    ) -> None:
        released = self.released_features()
        if any(f["feature"] == feature for f in released):
            return
        released.append(
            {
                "feature": feature,
                "commit_sha": commit_sha,
                "ts": dt.datetime.now(dt.timezone.utc).isoformat(),
                "release_run_id": release_run_id,
            }
        )
        self.released_path.write_text(json.dumps(released, indent=2))

    # ── Signals: production issues, from agentra's own monitoring (debug-prod) ──
    # or from customer bug reports pulled in via feedback_fetch_command. Same
    # ledger either way -- Discovery Agent treats a confirmed bug as a confirmed
    # bug regardless of who/what found it.

    def _repo_url(self) -> str | None:
        try:
            result = subprocess.run(
                ["git", "-C", str(self.repo), "remote", "get-url", "origin"],
                capture_output=True, text=True, timeout=10,
            )
        except (subprocess.SubprocessError, OSError):
            return None
        return result.stdout.strip() if result.returncode == 0 else None

    def known_bugs(self) -> list[dict]:
        repo_url = self._repo_url()
        if repo_url:
            try:
                from agentra.connectors import github_issues

                issues = github_issues.list_open_issues(repo_url, labels=[_BUG_LABEL])
                return [_github_bug_to_dict(i) for i in issues]
            except Exception:
                logger.warning("known_bugs: GitHub Issues unavailable for %s, using local mirror", repo_url, exc_info=True)
        return self._local_known_bugs()

    def _local_known_bugs(self) -> list[dict]:
        if not self.known_bugs_path.exists():
            return []
        return json.loads(self.known_bugs_path.read_text())

    def record_known_bug(
        self,
        run_id: str,
        severity: str,
        diagnosis: str,
        proposed_fix: str,
        source: str = "prod-monitoring",
        external_id: str | None = None,
    ) -> None:
        bugs = self._local_known_bugs()
        if external_id and any(b.get("external_id") == external_id for b in bugs):
            return  # already recorded -- feedback_fetch_command may return it again

        repo_url = self._repo_url()
        if repo_url and external_id is None:
            try:
                from agentra.connectors import github_issues

                body = f"Severity: {severity}\nSource: {source}\n\nProposed fix:\n{proposed_fix}"
                created = github_issues.create_issue(repo_url, diagnosis, body, labels=[_BUG_LABEL])
                external_id = str(created["number"])
            except Exception:
                logger.warning("record_known_bug: failed to create a GitHub issue for %s, recording locally only", repo_url, exc_info=True)

        bugs.append(
            {
                "run_id": run_id,
                "severity": severity,
                "diagnosis": diagnosis,
                "proposed_fix": proposed_fix,
                "source": source,
                "external_id": external_id,
            }
        )
        self.known_bugs_path.write_text(json.dumps(bugs, indent=2))

    def clear_known_bug(self, id_: str, resolution_note: str | None = None) -> None:
        # Match on either run_id or external_id -- a bug entry can carry both (this repo's
        # own known_bugs.json has both for a human-sourced entry), and an LLM resolving it
        # from check_backlog's raw JSON dump has no way to know which one is "the" id without
        # this being lenient. Confirmed live: an autonomous cycle passed external_id while
        # this only matched run_id, so the clear silently no-op'd and the bug never left the
        # backlog despite the agent believing it had resolved it.
        #
        # resolution_note: what actually shipped to fix this (feature name + commit) --
        # callers that know it should pass it, so the closed GitHub issue itself carries
        # a real "shipped" record instead of a content-free "Resolved by agentra."
        repo_url = self._repo_url()
        if repo_url and id_.isdigit():
            try:
                from agentra.connectors import github_issues

                github_issues.close_issue(repo_url, int(id_), comment=resolution_note or "Resolved by agentra.")
            except Exception:
                logger.warning("clear_known_bug: failed to close GitHub issue #%s on %s", id_, repo_url, exc_info=True)

        bugs = [b for b in self._local_known_bugs() if b.get("run_id") != id_ and b.get("external_id") != id_]
        self.known_bugs_path.write_text(json.dumps(bugs, indent=2))

    def record_failure(self, run_id: str, step_name: str, text: str, severity: str = "high") -> None:
        """The one place a failed agent turn's full output should be
        reported to -- see is_transient_failure's docstring above for the
        permanent-vs-transient policy this implements."""
        if is_transient_failure(text):
            self.log(run_id, f"{step_name} failed (transient, not filed as a bug): {text[:200]}")
            return
        self.record_known_bug(
            run_id, severity, f"{step_name} failed during an autonomous cycle", text[:2000], source="autonomous-failure"
        )

    # ── Queue: feature requests, from customers or added by an admin. Considered
    # by Discovery Agent above its own autonomous ideation, below real signals. ──

    def feature_queue(self) -> list[dict]:
        repo_url = self._repo_url()
        if repo_url:
            try:
                from agentra.connectors import github_issues

                issues = github_issues.list_open_issues(repo_url, labels=[_FEATURE_LABEL])
                return [_github_feature_to_dict(i) for i in issues]
            except Exception:
                logger.warning("feature_queue: GitHub Issues unavailable for %s, using local mirror", repo_url, exc_info=True)
        return self._local_feature_queue()

    def _local_feature_queue(self) -> list[dict]:
        if not self.feature_queue_path.exists():
            return []
        return json.loads(self.feature_queue_path.read_text())

    def record_feature_request(
        self,
        description: str,
        source: str = "customer",
        external_id: str | None = None,
    ) -> None:
        queue = self._local_feature_queue()
        if external_id and any(f.get("external_id") == external_id for f in queue):
            return

        repo_url = self._repo_url()
        if repo_url and external_id is None:
            try:
                from agentra.connectors import github_issues

                created = github_issues.create_issue(repo_url, description, f"Source: {source}", labels=[_FEATURE_LABEL])
                external_id = str(created["number"])
            except Exception:
                logger.warning("record_feature_request: failed to create a GitHub issue for %s, recording locally only", repo_url, exc_info=True)

        queue.append({"description": description, "source": source, "external_id": external_id})
        self.feature_queue_path.write_text(json.dumps(queue, indent=2))

    def clear_feature_request(self, external_id: str, resolution_note: str | None = None) -> None:
        repo_url = self._repo_url()
        if repo_url and external_id.isdigit():
            try:
                from agentra.connectors import github_issues

                github_issues.close_issue(repo_url, int(external_id), comment=resolution_note or "Resolved by agentra.")
            except Exception:
                logger.warning("clear_feature_request: failed to close GitHub issue #%s on %s", external_id, repo_url, exc_info=True)

        queue = [f for f in self._local_feature_queue() if f.get("external_id") != external_id]
        self.feature_queue_path.write_text(json.dumps(queue, indent=2))

    # ── Settings: the current objective. Read by default so --objective becomes
    # optional; `agentra objective set/show` manages this file directly. ──────

    _OBJECTIVE_VARIABLE = "AGENTRA_OBJECTIVE"

    def get_objective(self) -> str | None:
        objective = None
        if self.objective_path.exists():
            try:
                import yaml

                data = yaml.safe_load(self.objective_path.read_text()) or {}
            except ImportError:
                data = {}
                for line in self.objective_path.read_text().splitlines():
                    if line.startswith("objective:"):
                        data["objective"] = line.split(":", 1)[1].strip().strip('"')
            objective = data.get("objective")

        repo_url = self._repo_url()
        if repo_url:
            try:
                from agentra.connectors import github_variables

                remote_vars = github_variables.list_variables(repo_url)
                if self._OBJECTIVE_VARIABLE in remote_vars:
                    objective = remote_vars[self._OBJECTIVE_VARIABLE]
            except Exception:
                logger.warning("get_objective: GitHub Variables unavailable for %s, using local mirror", repo_url, exc_info=True)
        return objective

    def set_objective(self, objective: str) -> Path:
        content = {
            "objective": objective,
            "updated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        }
        try:
            import yaml

            self.objective_path.write_text(yaml.safe_dump(content, sort_keys=False))
        except ImportError:
            self.objective_path.write_text(
                f'objective: "{objective}"\nupdated_at: "{content["updated_at"]}"\n'
            )

        repo_url = self._repo_url()
        if repo_url:
            try:
                from agentra.connectors import github_variables

                github_variables.set_variable(repo_url, self._OBJECTIVE_VARIABLE, objective)
            except Exception:
                logger.warning("set_objective: failed to sync to GitHub Variables for %s, local file still saved", repo_url, exc_info=True)
        return self.objective_path

    # ── Feedback sync checkpoint: how far feedback_fetch_command has been read,
    # so each cycle only asks for what's new since last time. ────────────────

    def feedback_sync_state(self) -> dict:
        if not self.feedback_sync_state_path.exists():
            return {}
        return json.loads(self.feedback_sync_state_path.read_text())

    def update_feedback_sync_state(self, last_synced_at: str) -> None:
        self.feedback_sync_state_path.write_text(json.dumps({"last_synced_at": last_synced_at}, indent=2))

    # ── Codebase spec cache checkpoint: the commit SHA the last
    # architecture/codebase.md scan was generated at. Implementation Agent
    # is the only agent that commits source changes, so an unchanged HEAD
    # since this SHA means the repo genuinely hasn't moved and the cached
    # scan is still accurate -- see agents/codebase.py's run_cached(). ────

    def codebase_spec_commit(self) -> str | None:
        if not self.codebase_spec_commit_path.exists():
            return None
        return json.loads(self.codebase_spec_commit_path.read_text()).get("commit_sha")

    def set_codebase_spec_commit(self, commit_sha: str) -> None:
        self.codebase_spec_commit_path.write_text(json.dumps({"commit_sha": commit_sha}, indent=2))

    # ── Standups: TASK-019. "Yesterday" comes from these -- the one place in
    # .agentra/ with real per-event timestamps (shipped/known_bugs/feature_queue
    # are point-in-time snapshots, not event logs). "Today" is just the current
    # backlog (known_bugs/feature_queue/objective), read directly by the caller. ──

    def recent_log_lines(self, since: dt.datetime) -> list[str]:
        """Every timestamped line across all run logs at or after `since`,
        oldest first. The run logs are the only append-only, per-event
        record in .agentra/ -- shipped_features()/known_bugs() are current
        snapshots with no history of *when* an entry was added."""
        lines: list[str] = []
        if not self.log_root.is_dir():
            return lines
        for path in self.log_root.glob("*.log"):
            for raw_line in path.read_text().splitlines():
                if not raw_line.startswith("["):
                    continue
                ts_str, _, rest = raw_line[1:].partition("] ")
                try:
                    ts = dt.datetime.fromisoformat(ts_str)
                except ValueError:
                    continue
                if ts >= since:
                    lines.append(f"[{ts.isoformat()}] {rest}")
        lines.sort()
        return lines

    def record_standup(self, date_str: str, content: str) -> Path:
        self.standups_root.mkdir(parents=True, exist_ok=True)
        path = self.standups_root / f"{date_str}.md"
        path.write_text(content)
        return path

    def get_standup(self, date_str: str) -> str | None:
        path = self.standups_root / f"{date_str}.md"
        return path.read_text() if path.exists() else None

    def latest_standup(self) -> dict | None:
        if not self.standups_root.is_dir():
            return None
        dated = sorted(self.standups_root.glob("*.md"), key=lambda p: p.stem)
        if not dated:
            return None
        latest = dated[-1]
        date_str = latest.stem
        json_path = self.standups_root / f"{date_str}.json"
        
        updates = None
        if json_path.exists():
            try:
                updates = json.loads(json_path.read_text())
            except Exception:
                pass
                
        return {
            "date": date_str,
            "content": latest.read_text(),
            "updates": updates
        }

    # ── Live Standup Channel ────────────────────────────────────────────────
    # One shared transcript per day (not per-agent, unlike agent_chat_path
    # below) -- every agent's opening status post and every human message +
    # routed reply lands in the same ordered list, same "one channel,
    # multiple participants" shape the dashboard renders. Scoped by date
    # like the written standup report it replaces was, so "today's standup"
    # still means one specific day's conversation, not an ever-growing log.

    def standup_channel_path(self, date_str: str) -> Path:
        return self.standups_root / f"{date_str}-channel.json"

    def get_standup_channel_messages(self, date_str: str) -> list[dict]:
        path = self.standup_channel_path(date_str)
        if not path.exists():
            return []
        try:
            return json.loads(path.read_text())
        except Exception:
            return []

    def record_standup_channel_message(self, date_str: str, sender: str, text: str) -> dict:
        self.standups_root.mkdir(parents=True, exist_ok=True)
        messages = self.get_standup_channel_messages(date_str)
        message = {"sender": sender, "text": text, "ts": dt.datetime.now(dt.timezone.utc).isoformat()}
        messages.append(message)
        self.standup_channel_path(date_str).write_text(json.dumps(messages, indent=2))
        return message

    # ── Agent Chat & Work Updates ─────────────────────────────────────────────

    def agent_chat_path(self, agent_id: str) -> Path:
        return self.root / f"agent_chats_{agent_id}.json"

    def get_agent_chat_messages(self, agent_id: str) -> list[dict]:
        path = self.agent_chat_path(agent_id)
        if not path.exists():
            return []
        try:
            return json.loads(path.read_text())
        except Exception:
            return []

    def record_agent_chat_message(self, agent_id: str, sender: str, text: str) -> None:
        messages = self.get_agent_chat_messages(agent_id)
        messages.append({
            "sender": sender,
            "text": text,
            "ts": dt.datetime.now(dt.timezone.utc).isoformat()
        })
        self.agent_chat_path(agent_id).write_text(json.dumps(messages, indent=2))

    # Claude Agent SDK session id for this agent's chat -- lets server.py
    # resume the exact prior session (full context, same as `claude -c`)
    # instead of a fresh cold-start subprocess reconstructing a crude
    # "Human: ...\nAgent: ..." text blob from the last few messages on every
    # single turn. One session per (app, agent_id), same scope as the chat
    # history itself; a separate file rather than folding into the chat
    # messages JSON so a corrupt/reset session doesn't need touching the
    # actual conversation log.
    def agent_session_path(self, agent_id: str) -> Path:
        return self.root / f"agent_session_{agent_id}.json"

    def get_agent_session_id(self, agent_id: str) -> str | None:
        path = self.agent_session_path(agent_id)
        if not path.exists():
            return None
        try:
            return json.loads(path.read_text()).get("session_id")
        except Exception:
            return None

    def set_agent_session_id(self, agent_id: str, session_id: str) -> None:
        self.agent_session_path(agent_id).write_text(json.dumps({"session_id": session_id}))

    def get_work_updates(self) -> list[dict]:
        if not self.work_updates_path.exists():
            return []
        try:
            return json.loads(self.work_updates_path.read_text())
        except Exception:
            return []

    def record_work_update(self, agent_id: str, description: str) -> None:
        updates = self.get_work_updates()
        updates.append({
            "agent_id": agent_id,
            "description": description,
            "ts": dt.datetime.now(dt.timezone.utc).isoformat()
        })
        self.work_updates_path.write_text(json.dumps(updates, indent=2))

    def append_documentation(self, entry: str) -> None:
        """Appends one dated line to architecture/documentation.md's
        running changelog, instead of overwriting the whole file the way
        write() does -- the top of documentation.md is a static
        architecture description (human-edited via the dashboard's Edit
        App modal), the changelog lives below it as its own section so
        recording a shipped feature here never clobbers that description.

        Deliberately separate from record_work_update: that's a
        structured per-agent ledger the dashboard's "Latest Work Done"
        card reads (JSON, one entry replaces nothing, all history kept)
        -- this is the human-readable prose trail of what actually
        shipped, meant to accumulate as living documentation rather than
        an array nobody browses as JSON."""
        existing = self.read("architecture", "documentation") or ""
        marker = "## Changelog"
        if marker not in existing:
            existing = existing.rstrip() + f"\n\n{marker}\n" if existing else f"{marker}\n"
        date_str = dt.datetime.now(dt.timezone.utc).date().isoformat()
        updated = existing.rstrip() + f"\n- {date_str}: {entry}\n"
        self.write("architecture", "documentation", updated)
