"""Persistent memory store, scoped to the target repo being improved.

Mirrors the layout from vision.md section 9: architecture, decisions,
features, metrics, failures. Lives at <repo>/.agentra/memory/ so it travels
with the repo and accumulates across runs.

App-agnostic by design: everything here is plain JSON/YAML files agentra
owns and reads/writes itself. Getting real data INTO these files (customer
feedback from whatever database a given app uses, an objective set via
whatever admin UI a given app has) is the job of a per-app adapter command
(EnvironmentConfig.feedback_fetch_command, invoked by orchestrator.py/
brain.py) -- agentra's own code never talks to Firestore/Postgres/anything
app-specific directly.

Git hygiene
-----------
On first use, Memory writes a .agentra/.gitignore into the target repo so that:

  Committed (audit trail, config)       Not committed (noisy per-run data)
  ──────────────────────────────────    ────────────────────────────────────
  memory/  (architecture, decisions,    logs/  (verbose timestamped traces)
           features, metrics, failures)
  shipped.json
  known_bugs.json
  feature_queue.json
  objective.yaml
  feedback_sync_state.json
  environments.yaml

This means the memory system travels with the repo across clones, CI runners,
and contributors, while run logs stay local.
"""

import datetime as dt
import json
from pathlib import Path

CATEGORIES = ("architecture", "decisions", "features", "metrics", "failures")

# Written to <repo>/.agentra/.gitignore on first use. We commit the audit
# trail and config; ignore only the verbose per-run logs that add noise
# without value in history.
_GITIGNORE_CONTENT = """\
# Generated by agentra — do not edit manually.
# Commit the audit trail; ignore per-run logs.

# ── ignored ──────────────────────────────────────────────────────────────────
logs/

# ── tracked (listed for clarity; git tracks everything not ignored) ───────────
# memory/
# shipped.json
# known_bugs.json
# feature_queue.json
# objective.yaml
# feedback_sync_state.json
# environments.yaml
"""


def _ensure_gitignore(root: Path) -> None:
    """Write .agentra/.gitignore if it is missing or doesn't ignore logs/."""
    gitignore = root / ".gitignore"
    if gitignore.exists() and "logs/" in gitignore.read_text():
        return  # already correct, skip the write
    gitignore.write_text(_GITIGNORE_CONTENT)


class Memory:
    def __init__(self, repo: Path):
        self.root = repo / ".agentra"
        self.memory_root = self.root / "memory"
        self.log_root = self.root / "logs"
        self.shipped_path = self.root / "shipped.json"
        self.known_bugs_path = self.root / "known_bugs.json"
        self.feature_queue_path = self.root / "feature_queue.json"
        self.objective_path = self.root / "objective.yaml"
        self.feedback_sync_state_path = self.root / "feedback_sync_state.json"
        self.standups_root = self.root / "standups"
        for category in CATEGORIES:
            (self.memory_root / category).mkdir(parents=True, exist_ok=True)
        self.log_root.mkdir(parents=True, exist_ok=True)
        _ensure_gitignore(self.root)

    def write(self, category: str, name: str, content: str) -> Path:
        if category not in CATEGORIES:
            raise ValueError(f"unknown memory category: {category}")
        path = self.memory_root / category / f"{name}.md"
        # The category directory can vanish between __init__ and this call -- e.g.
        # implementation.py's _checkout_feature_branch does `git clean -fd .agentra/`
        # then `git checkout -B <feature_branch>`, and git doesn't track empty
        # directories, so a category with no committed file in it (e.g. a repo's
        # first-ever feature under memory/features/) simply doesn't come back after
        # that checkout. Recreate it defensively rather than assume __init__'s mkdir
        # still holds.
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        return path

    def read(self, category: str, name: str) -> str | None:
        path = self.memory_root / category / f"{name}.md"
        return path.read_text() if path.exists() else None

    def log(self, run_id: str, content: str) -> Path:
        path = self.log_root / f"{run_id}.log"
        self.log_root.mkdir(parents=True, exist_ok=True)
        with path.open("a") as f:
            timestamp = dt.datetime.now(dt.timezone.utc).isoformat()
            f.write(f"[{timestamp}] {content}\n")
        return path

    def shipped_features(self) -> list[str]:
        if not self.shipped_path.exists():
            return []
        return json.loads(self.shipped_path.read_text())

    def record_shipped(self, feature: str) -> None:
        features = self.shipped_features()
        if feature not in features:
            features.append(feature)
            self.shipped_path.write_text(json.dumps(features, indent=2))

    # ── Signals: production issues, from agentra's own monitoring (debug-prod) ──
    # or from customer bug reports pulled in via feedback_fetch_command. Same
    # ledger either way -- Discovery Agent treats a confirmed bug as a confirmed
    # bug regardless of who/what found it.

    def known_bugs(self) -> list[dict]:
        if not self.known_bugs_path.exists():
            return []
        return json.loads(self.known_bugs_path.read_text())

    def record_known_bug(
        self,
        run_id: str,
        severity: str,
        diagnosis: str,
        proposed_fix: str,
        source: str = "prod-monitoring",
        external_id: str | None = None,
    ) -> None:
        bugs = self.known_bugs()
        if external_id and any(b.get("external_id") == external_id for b in bugs):
            return  # already recorded -- feedback_fetch_command may return it again
        bugs.append(
            {
                "run_id": run_id,
                "severity": severity,
                "diagnosis": diagnosis,
                "proposed_fix": proposed_fix,
                "source": source,
                "external_id": external_id,
            }
        )
        self.known_bugs_path.write_text(json.dumps(bugs, indent=2))

    def clear_known_bug(self, id_: str) -> None:
        # Match on either run_id or external_id -- a bug entry can carry both (this repo's
        # own known_bugs.json has both for a human-sourced entry), and an LLM resolving it
        # from check_backlog's raw JSON dump has no way to know which one is "the" id without
        # this being lenient. Confirmed live: an autonomous cycle passed external_id while
        # this only matched run_id, so the clear silently no-op'd and the bug never left the
        # backlog despite the agent believing it had resolved it.
        bugs = [b for b in self.known_bugs() if b.get("run_id") != id_ and b.get("external_id") != id_]
        self.known_bugs_path.write_text(json.dumps(bugs, indent=2))

    # ── Queue: feature requests, from customers or added by an admin. Considered
    # by Discovery Agent above its own autonomous ideation, below real signals. ──

    def feature_queue(self) -> list[dict]:
        if not self.feature_queue_path.exists():
            return []
        return json.loads(self.feature_queue_path.read_text())

    def record_feature_request(
        self,
        description: str,
        source: str = "customer",
        external_id: str | None = None,
    ) -> None:
        queue = self.feature_queue()
        if external_id and any(f.get("external_id") == external_id for f in queue):
            return
        queue.append({"description": description, "source": source, "external_id": external_id})
        self.feature_queue_path.write_text(json.dumps(queue, indent=2))

    def clear_feature_request(self, external_id: str) -> None:
        queue = [f for f in self.feature_queue() if f.get("external_id") != external_id]
        self.feature_queue_path.write_text(json.dumps(queue, indent=2))

    # ── Settings: the current objective. Read by default so --objective becomes
    # optional; `agentra objective set/show` manages this file directly. ──────

    def get_objective(self) -> str | None:
        if not self.objective_path.exists():
            return None
        try:
            import yaml

            data = yaml.safe_load(self.objective_path.read_text()) or {}
        except ImportError:
            data = {}
            for line in self.objective_path.read_text().splitlines():
                if line.startswith("objective:"):
                    data["objective"] = line.split(":", 1)[1].strip().strip('"')
        return data.get("objective")

    def set_objective(self, objective: str) -> Path:
        content = {
            "objective": objective,
            "updated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        }
        try:
            import yaml

            self.objective_path.write_text(yaml.safe_dump(content, sort_keys=False))
        except ImportError:
            self.objective_path.write_text(
                f'objective: "{objective}"\nupdated_at: "{content["updated_at"]}"\n'
            )
        return self.objective_path

    # ── Feedback sync checkpoint: how far feedback_fetch_command has been read,
    # so each cycle only asks for what's new since last time. ────────────────

    def feedback_sync_state(self) -> dict:
        if not self.feedback_sync_state_path.exists():
            return {}
        return json.loads(self.feedback_sync_state_path.read_text())

    def update_feedback_sync_state(self, last_synced_at: str) -> None:
        self.feedback_sync_state_path.write_text(json.dumps({"last_synced_at": last_synced_at}, indent=2))

    # ── Standups: TASK-019. "Yesterday" comes from these -- the one place in
    # .agentra/ with real per-event timestamps (shipped/known_bugs/feature_queue
    # are point-in-time snapshots, not event logs). "Today" is just the current
    # backlog (known_bugs/feature_queue/objective), read directly by the caller. ──

    def recent_log_lines(self, since: dt.datetime) -> list[str]:
        """Every timestamped line across all run logs at or after `since`,
        oldest first. The run logs are the only append-only, per-event
        record in .agentra/ -- shipped_features()/known_bugs() are current
        snapshots with no history of *when* an entry was added."""
        lines: list[str] = []
        if not self.log_root.is_dir():
            return lines
        for path in self.log_root.glob("*.log"):
            for raw_line in path.read_text().splitlines():
                if not raw_line.startswith("["):
                    continue
                ts_str, _, rest = raw_line[1:].partition("] ")
                try:
                    ts = dt.datetime.fromisoformat(ts_str)
                except ValueError:
                    continue
                if ts >= since:
                    lines.append(f"[{ts.isoformat()}] {rest}")
        lines.sort()
        return lines

    def record_standup(self, date_str: str, content: str) -> Path:
        self.standups_root.mkdir(parents=True, exist_ok=True)
        path = self.standups_root / f"{date_str}.md"
        path.write_text(content)
        return path

    def get_standup(self, date_str: str) -> str | None:
        path = self.standups_root / f"{date_str}.md"
        return path.read_text() if path.exists() else None

    def latest_standup(self) -> dict | None:
        if not self.standups_root.is_dir():
            return None
        dated = sorted(self.standups_root.glob("*.md"), key=lambda p: p.stem)
        if not dated:
            return None
        latest = dated[-1]
        return {"date": latest.stem, "content": latest.read_text()}
