"""Persistent memory store, scoped to the target repo being improved.

Mirrors the layout from vision.md section 9: architecture, decisions,
features, metrics, failures. Lives at <repo>/.agentos/memory/ so it travels
with the repo and accumulates across runs.

Git hygiene
-----------
On first use, Memory writes a .agentos/.gitignore into the target repo so that:

  Committed (audit trail, config)       Not committed (noisy per-run data)
  ──────────────────────────────────    ────────────────────────────────────
  memory/  (architecture, decisions,    logs/  (verbose timestamped traces)
           features, metrics, failures)
  shipped.json
  known_bugs.json
  environments.yaml

This means the memory system travels with the repo across clones, CI runners,
and contributors, while run logs stay local.
"""

import datetime as dt
import json
from pathlib import Path

CATEGORIES = ("architecture", "decisions", "features", "metrics", "failures")

# Written to <repo>/.agentos/.gitignore on first use.  We commit the audit
# trail (memory/, shipped.json, known_bugs.json, environments.yaml) and ignore
# only the verbose per-run logs that add noise without value in history.
_GITIGNORE_CONTENT = """\
# Generated by agentos — do not edit manually.
# Commit the audit trail; ignore per-run logs.

# ── ignored ──────────────────────────────────────────────────────────────────
logs/

# ── tracked (listed for clarity; git tracks everything not ignored) ───────────
# memory/
# shipped.json
# known_bugs.json
# environments.yaml
"""


def _ensure_gitignore(root: Path) -> None:
    """Write .agentos/.gitignore if it is missing or doesn't ignore logs/."""
    gitignore = root / ".gitignore"
    if gitignore.exists() and "logs/" in gitignore.read_text():
        return  # already correct, skip the write
    gitignore.write_text(_GITIGNORE_CONTENT)


class Memory:
    def __init__(self, repo: Path):
        self.root = repo / ".agentos"
        self.memory_root = self.root / "memory"
        self.log_root = self.root / "logs"
        self.shipped_path = self.root / "shipped.json"
        self.known_bugs_path = self.root / "known_bugs.json"
        for category in CATEGORIES:
            (self.memory_root / category).mkdir(parents=True, exist_ok=True)
        self.log_root.mkdir(parents=True, exist_ok=True)
        _ensure_gitignore(self.root)

    def write(self, category: str, name: str, content: str) -> Path:
        if category not in CATEGORIES:
            raise ValueError(f"unknown memory category: {category}")
        path = self.memory_root / category / f"{name}.md"
        path.write_text(content)
        return path

    def read(self, category: str, name: str) -> str | None:
        path = self.memory_root / category / f"{name}.md"
        return path.read_text() if path.exists() else None

    def log(self, run_id: str, content: str) -> Path:
        path = self.log_root / f"{run_id}.log"
        with path.open("a") as f:
            timestamp = dt.datetime.now(dt.timezone.utc).isoformat()
            f.write(f"[{timestamp}] {content}\n")
        return path

    def shipped_features(self) -> list[str]:
        if not self.shipped_path.exists():
            return []
        return json.loads(self.shipped_path.read_text())

    def record_shipped(self, feature: str) -> None:
        features = self.shipped_features()
        if feature not in features:
            features.append(feature)
            self.shipped_path.write_text(json.dumps(features, indent=2))

    def known_bugs(self) -> list[dict]:
        if not self.known_bugs_path.exists():
            return []
        return json.loads(self.known_bugs_path.read_text())

    def record_known_bug(self, run_id: str, severity: str, diagnosis: str, proposed_fix: str) -> None:
        bugs = self.known_bugs()
        bugs.append(
            {
                "run_id": run_id,
                "severity": severity,
                "diagnosis": diagnosis,
                "proposed_fix": proposed_fix,
            }
        )
        self.known_bugs_path.write_text(json.dumps(bugs, indent=2))

    def clear_known_bug(self, run_id: str) -> None:
        bugs = [b for b in self.known_bugs() if b.get("run_id") != run_id]
        self.known_bugs_path.write_text(json.dumps(bugs, indent=2))
